
spring:
  data:
    mongodb:
      uri: mongodb+srv://ashrafulislam85321:KetttkwatooEqbam@cluster0.dhzurv9.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: persondb
      auto-index-creation: true
  application:
    name: Making Rest Api

server:
  port: 8080
  servlet:
    context-path: /api



